[package]
name = "totally-not-malware"
version = "0.1.0"
edition = "2021"

[dependencies]
iced = { version = "0.7", features = ["image"] }

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

[profile.release]
panic = "abort"
lto = true
strip = true
codegen-units = 1
